### ISSUE TITLE
TypeError: Cannot destructure property 'id' of 'infoReply' as it is undefined.

### ISSUE THREAD

**Issue by steveworley** [cipherstash/stashjs#1]
This occurred when trying to query for a record - this caused a V8 panic which resulted in the application crashing.

**Example query**
```
 {
	"formId": { "eq": "226d1176-b6c7-4acf-80a0-2caaca108d0e" }
}

```

Error details:
```
./quant/cipherstash-proxy/node_modules/.pnpm/@cipherstash+stashjs@0.2.23/node_modules/@cipherstash/stashjs/dist/stash.js:99
        const { id, indexes: encryptedMappings } = infoReply;
                ^

TypeError: Cannot destructure property 'id' of 'infoReply' as it is undefined.
    at Stash.unpackCollection (./quant/cipherstash-proxy/node_modules/.pnpm/@cipherstash+stashjs@0.2.23/node_modules/@cipherstash/stashjs/dist/stash.js:99:17)
    at Object.callback (./quant/cipherstash-proxy/node_modules/.pnpm/@cipherstash+stashjs@0.2.23/node_modules/@cipherstash/stashjs/dist/stash.js:80:36)
    at Object.onReceiveStatus (./quant/cipherstash-proxy/node_modules/.pnpm/@grpc+grpc-js@1.3.6/node_modules/@grpc/grpc-js/build/src/client.js:179:36)
    at Object.onReceiveStatus (./quant/cipherstash-proxy/node_modules/.pnpm/@grpc+grpc-js@1.3.6/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (./quant/cipherstash-proxy/node_modules/.pnpm/@grpc+grpc-js@1.3.6/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at ./quant/cipherstash-proxy/node_modules/.pnpm/@grpc+grpc-js@1.3.6/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
 1: 0x101317585 node::Abort() (.cold.1) [/.nvm/versions/node/v14.17.3/bin/node]
 2: 0x1000b25c9 node::Abort() [/.nvm/versions/node/v14.17.3/bin/node]
 3: 0x1000b3cdc node::errors::TriggerUncaughtException(v8::FunctionCallbackInfo<v8::Value> const&) [/.nvm/versions/node/v14.17.3/bin/node]
 4: 0x100268328 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/.nvm/versions/node/v14.17.3/bin/node]
 5: 0x1002678bc v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/.nvm/versions/node/v14.17.3/bin/node]
 6: 0x100266fe2 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/.nvm/versions/node/v14.17.3/bin/node]
 7: 0x100a8a9f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/.nvm/versions/node/v14.17.3/bin/node]
[1]    26394 abort      npm run start
```

**Comment by coderdan** [comment]
Update: this appears to be happening when trying to create a collection that already exists. CC/ @freshtonic

**Comment by freshtonic** [comment]
This is out of date and has been fixed in the monorepo
